apiVersion: v1
kind: Namespace
metadata:
  name: canary
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: web
  name: web
  namespace: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: argoproj/rollouts-demo:blue
        name: blue
        ports:
        - containerPort: 80
  strategy:
    canary:
      canaryService: canary-svc
      maxSurge: 25%
      maxUnavailable: 0%
      stableService: stable-svc
      steps:
      - setWeight: 25
      - pause:
          duration: 5m
      - setWeight: 50
      - pause:
          duration: 5m      
---
apiVersion: v1
kind: Service
metadata:
  name: canary-svc
  namespace: canary
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: stable-svc
  namespace: canary
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
